---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# GetSoilPars

<!-- badges: start -->
<!-- badges: end -->

The goal of GetSoilPars is to retrieve soil texture parameters by geographic coordinates fromthe BUEK2000 soil map.

## Installation

You can install the development version of GetSoilPars from [GitHub](https://github.com/) with:

``` r
# install.packages("pak")
pak::pak("HenningKage/GetSoilPars")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(GetSoilPars)
library(dplyr)
library(sf)
## basic example code


geoLaenge <- 11.5
geoBreite <- 48.1


# transfer geographic coordinates to a point object
Point <- getPointCoordinates (geoLaenge, geoBreite, crs = "EPSG:25832")

# get a local part of the soil map
Map <- getSoilMap(Point)#, BUEK2000_Kartenblaetter)

# retrieve the soil polygon for the location
SPolygon <- getSoilPolygon (Point, Map)

# retrieve the soil texture data for the soil profile of the "Leitboden"
SoilTexture <- getSoilTexture (SPolygon, short = TRUE, fill_NA = TRUE)
str(SoilTexture)

```


```{r example2}
# same as above but in one step
SoilTexture2 <- getPointTextureData (geoLaenge, geoBreite, short = TRUE, fill_NA = TRUE)
#SoilTexture2



```

